CREATE DATABASE IF NOT EXISTS ioe;

USE ioe;

drop table if exists transactions CASCADE;
drop table if exists users CASCADE;
drop table if exists admins CASCADE;


CREATE TABLE `users` (
    `USER_ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(70) NOT NULL,
    `EMAIL_ID` VARCHAR(70) NOT NULL,
    `USERNAME` VARCHAR(70) NOT NULL UNIQUE,
    `PASSWORD` VARCHAR(100) NOT NULL ,
    `USER_KEY` VARCHAR(500) NOT NULL UNIQUE
);

CREATE TABLE `admins`
(
    `ADMIN_ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `ADMIN_NAME` VARCHAR(70) NOT NULL,
    `EMAIL_ID` VARCHAR(70) NOT NULL,
    `USERNAME` VARCHAR(70) NOT NULL UNIQUE,
    `PASSWORD` VARCHAR(70) NOT NULL,
    `ADMIN_KEY` VARCHAR(500) NOT NULL UNIQUE
);

CREATE TABLE `transactions`
(
    `TRANSACTION_ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` INT NOT NULL ,
    `WATT/SECOND` DECIMAL(5,2) NOT NULL,
    `TYPE` ENUM("GIVE","TAKE") NOT NULL,
    `TIMESTAMP` timestamp NOT NULL DEFAULT NOW(),
    FOREIGN KEY(`USER_ID`) REFERENCES users(`USER_ID`)
    ON UPDATE CASCADE ON DELETE CASCADE
);
